name: Simple Backup Workflow

on:
  workflow_call:

jobs:
  simple-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Backup Workflow Called
        run: echo "âœ… Backup workflow was successfully called!"
